// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ65udBWsjRW68vL-PgtmBPTQCF1AxbPc',
    appId: '1:10001781780:web:1b0c8dd0d4a4d3cd0b8301',
    messagingSenderId: '10001781780',
    projectId: 'donobox-11ec0',
    authDomain: 'donobox-11ec0.firebaseapp.com',
    storageBucket: 'donobox-11ec0.appspot.com',
    measurementId: 'G-DVDHJNDMKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVFA2NRJ214wpGz_h991jYbYpLm04pKp0',
    appId: '1:10001781780:android:9cdcaacd4bceb6dc0b8301',
    messagingSenderId: '10001781780',
    projectId: 'donobox-11ec0',
    storageBucket: 'donobox-11ec0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEVcJCgV0j5CzdTSb8N1ZFmdlKz_EBxfE',
    appId: '1:10001781780:ios:c246eb3abc13621b0b8301',
    messagingSenderId: '10001781780',
    projectId: 'donobox-11ec0',
    storageBucket: 'donobox-11ec0.appspot.com',
    iosClientId: '10001781780-kt7jf6sqbv11kl31c48q80b404abdgv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.donobox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEVcJCgV0j5CzdTSb8N1ZFmdlKz_EBxfE',
    appId: '1:10001781780:ios:c246eb3abc13621b0b8301',
    messagingSenderId: '10001781780',
    projectId: 'donobox-11ec0',
    storageBucket: 'donobox-11ec0.appspot.com',
    iosClientId: '10001781780-kt7jf6sqbv11kl31c48q80b404abdgv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.donobox',
  );
}
